{% set name = "pydl" %}
{% set version = "0.7.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': '8f35c97815b73e1da0cd67b56a051aa9768a88e46a1aad080d23c2a4cdc45b84'

build:
  number: 3
  entry_points:
    - get_juldate = pydl.goddard.astro:get_juldate_main
    - hogg_iau_name = pydl.pydlutils.misc:hogg_iau_name_main
    - compute_templates = pydl.pydlspec2d.spec1d:template_input_main
  script: python setup.py install --offline --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - astropy
    - scipy
    - matplotlib-base

test:
  imports:
    - pydl
    - pydl.goddard
    - pydl.photoop
    - pydl.pydlspec2d
    - pydl.pydlutils
  commands:
    - get_juldate --help
    - compute_templates --help

about:
  home: http://github.com/weaverba137/pydl
  license: BSD 3-clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: Python implementations of some functions from astronomical IDL libraries.
  description: |
    Python replacements for functions that are part of the IDL built-in
    library, or part of astronomical IDL libraries.  The emphasis is on
    reproducing results of the astronomical library functions.  Only the bare
    minimum of IDL built-in functions are implemented to support this. pydl is
    an Astropy affiliated package.
  doc_url: http://pydl.readthedocs.org/en/latest/
  dev_url: http://github.com/weaverba137/pydl

extra:
  recipe-maintainers:
    - mwcraig
    - weaverba137
