{% set name = "pydl" %}
{% set version = "1.0.1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': '5026e3b80fe413a13d363fbd526abb9107db638710584406243d02870b60087c'

build:
  number: 1
  entry_points:
    - get_juldate = pydl.goddard.astro:get_juldate_main
    - hogg_iau_name = pydl.pydlutils.misc:hogg_iau_name_main
    - compute_templates = pydl.pydlspec2d.spec1d:template_input_main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - astropy
    - scipy
    - matplotlib-base

test:
  imports:
    - pydl
    - pydl.goddard
    - pydl.photoop
    - pydl.pydlspec2d
    - pydl.pydlutils
  commands:
    - get_juldate --help
    - compute_templates --help

about:
  home: https://github.com/weaverba137/pydl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Python implementations of some functions from astronomical IDL libraries.
  description: |
    Python replacements for functions that are part of the IDL built-in
    library, or part of astronomical IDL libraries.  The emphasis is on
    reproducing results of the astronomical library functions.  Only the bare
    minimum of IDL built-in functions are implemented to support this. pydl is
    an Astropy affiliated package.
  doc_url: https://pydl.readthedocs.io/en/latest/
  dev_url: https://github.com/weaverba137/pydl

extra:
  recipe-maintainers:
    - mwcraig
    - weaverba137
