{% set name = "pydl" %}
{% set version = "0.7.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': '8f35c97815b73e1da0cd67b56a051aa9768a88e46a1aad080d23c2a4cdc45b84'

build:
  number: 6
  entry_points:
    - get_juldate = pydl.goddard.astro:get_juldate_main
    - hogg_iau_name = pydl.pydlutils.misc:hogg_iau_name_main
    - compute_templates = pydl.pydlspec2d.spec1d:template_input_main
  # Note: pip-based install fails due to wanting to download astropy-helpers
  # Also note: astropy-helpers needs the imp module which has been removed from 3.12.
  # script: {{ PYTHON }} -m pip install . -vv
  script:
    - "sed -r -e 's/import imp/import importlib as imp/' -i.bak ah_bootstrap.py"
    - "sed -r -e 's/import imp/import importlib as imp/' -i.bak astropy_helpers/astropy_helpers/utils.py"
    - "python setup.py install --offline --no-git --single-version-externally-managed --record=files.txt"
  # skip: true  # [py>311]

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - astropy
    - scipy
    - matplotlib-base

test:
  imports:
    - pydl
    - pydl.goddard
    - pydl.photoop
    - pydl.pydlspec2d
    - pydl.pydlutils
  commands:
    - get_juldate --help
    - compute_templates --help

about:
  home: https://github.com/weaverba137/pydl
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: Python implementations of some functions from astronomical IDL libraries.
  description: |
    Python replacements for functions that are part of the IDL built-in
    library, or part of astronomical IDL libraries.  The emphasis is on
    reproducing results of the astronomical library functions.  Only the bare
    minimum of IDL built-in functions are implemented to support this. pydl is
    an Astropy affiliated package.
  doc_url: https://pydl.readthedocs.io/en/latest/
  dev_url: https://github.com/weaverba137/pydl

extra:
  recipe-maintainers:
    - mwcraig
    - weaverba137
