{% set name = "pydl" %}
{% set version = "1.0.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': 'b6388837cc3252faec36695e4dd1de44cb4651b412392e55a60195f15a010289'

build:
  number: 1
  entry_points:
    - get_juldate = pydl.goddard.astro:get_juldate_main
    - hogg_iau_name = pydl.pydlutils.misc:hogg_iau_name_main
    - compute_templates = pydl.pydlspec2d.spec1d:template_input_main
  script: {{ PYTHON }} -m pip install . -vv
  # Note: pip-based install fails due to wanting to download astropy-helpers
  # Also note: astropy-helpers needs the imp module which has been removed from 3.12.
  #            It's not worth the effort to try to patch astropy-helpers for 3.12
  #            for this old version.
  # script: {{ PYTHON }} setup.py install --offline --no-git --single-version-externally-managed --record=files.txt
  skip: true  # [py>311]

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - astropy
    - scipy
    - matplotlib-base

test:
  imports:
    - pydl
    - pydl.goddard
    - pydl.photoop
    - pydl.pydlspec2d
    - pydl.pydlutils
  commands:
    - get_juldate --help
    - compute_templates --help

about:
  home: https://github.com/weaverba137/pydl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Python implementations of some functions from astronomical IDL libraries.
  description: |
    Python replacements for functions that are part of the IDL built-in
    library, or part of astronomical IDL libraries.  The emphasis is on
    reproducing results of the astronomical library functions.  Only the bare
    minimum of IDL built-in functions are implemented to support this. pydl is
    an Astropy affiliated package.
  doc_url: https://pydl.readthedocs.io/en/latest/
  dev_url: https://github.com/weaverba137/pydl

extra:
  recipe-maintainers:
    - mwcraig
    - weaverba137
